package httpadapter

import (
	"time"

	"github.com/galenos-pro/appointments-api/internal/domain"
)

// createAppointmentRequest es el contrato de entrada esperado desde Angular.
type createAppointmentRequest struct {
	PatientID string    `json:"patientId" binding:"required"`
	DoctorID  string    `json:"doctorId" binding:"required"`
	StartsAt  time.Time `json:"startsAt" binding:"required"`
	EndsAt    time.Time `json:"endsAt" binding:"required"`
	Reason    string    `json:"reason" binding:"required,max=500"`
}

// createPatientRequest es el cuerpo de POST /api/v1/pacientes. Replica los
// parámetros del SP WebPacienteAgregar_E_H; los campos opcionales son
// punteros para que el frontend envíe solo los que recopiló.
type createPatientRequest struct {
	PaternalSurname   *string    `json:"apellidoPaterno"`
	MaternalSurname   *string    `json:"apellidoMaterno"`
	FirstName         *string    `json:"primerNombre"`
	SecondName        *string    `json:"segundoNombre"`
	DateOfBirth       *time.Time `json:"fechaNacimiento"`
	DocIdentityID     *int64     `json:"idDocIdentidad"`
	DocumentNumber    *string    `json:"nroDocumento"`
	Phone             *string    `json:"telefono"`
	HomeAddress       *string    `json:"direccionDomicilio"`
	SexTypeID         *int64     `json:"idTipoSexo"`
	MaritalStatusID   *int64     `json:"idEstadoCivil"`
	BirthDistrictID   *int64     `json:"idDistritoNacimiento"`
	HomeDistrictID    *int64     `json:"idDistritoDomicilio"`
	InsuranceTypeID   *int64     `json:"idTipoSeguro"`
	OriginID          *int64     `json:"idProcedencia"`
	EducationDegreeID *int64     `json:"idGradoInstruccion"`
	OccupationTypeID  *int64     `json:"idTipoOcupacion"`
	HistoryNumber     *string    `json:"nroHistoriaClinica"`
	StateID           *int64     `json:"idEstado"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP.
func (r createPatientRequest) toDomain() domain.PatientCreate {
	return domain.PatientCreate{
		PaternalSurname:   r.PaternalSurname,
		MaternalSurname:   r.MaternalSurname,
		FirstName:         r.FirstName,
		SecondName:        r.SecondName,
		DateOfBirth:       r.DateOfBirth,
		DocIdentityID:     r.DocIdentityID,
		DocumentNumber:    r.DocumentNumber,
		Phone:             r.Phone,
		HomeAddress:       r.HomeAddress,
		SexTypeID:         r.SexTypeID,
		MaritalStatusID:   r.MaritalStatusID,
		BirthDistrictID:   r.BirthDistrictID,
		HomeDistrictID:    r.HomeDistrictID,
		InsuranceTypeID:   r.InsuranceTypeID,
		OriginID:          r.OriginID,
		EducationDegreeID: r.EducationDegreeID,
		OccupationTypeID:  r.OccupationTypeID,
		HistoryNumber:     r.HistoryNumber,
		StateID:           r.StateID,
	}
}

// updatePatientRequest es el cuerpo de PUT /api/v1/pacientes/:id. Repite los
// campos editables de domain.PatientUpdate para que el binding de Gin sea
// explícito en el adaptador HTTP.
type updatePatientRequest struct {
	BirthCountryID    *int64     `json:"birthCountryId"`
	MaternalSurname   *string    `json:"maternalSurname"`
	HomeAddress       *string    `json:"homeAddress"`
	OriginCountryID   *int64     `json:"originCountryId"`
	PaternalSurname   *string    `json:"paternalSurname"`
	FirstName         *string    `json:"firstName"`
	SecondName        *string    `json:"secondName"`
	ThirdName         *string    `json:"thirdName"`
	DateOfBirth       *time.Time `json:"dateOfBirth"`
	DocumentNumber    *string    `json:"documentNumber"`
	Phone             *string    `json:"phone"`
	Cellphone         *string    `json:"cellphone"`
	AutoGenerated     *string    `json:"autoGenerated"`
	SexTypeID         *int64     `json:"sexTypeId"`
	OriginID          *int64     `json:"originId"`
	EducationDegreeID *int64     `json:"educationDegreeId"`
	MaritalStatusID   *int64     `json:"maritalStatusId"`
	DocIdentityID     *int64     `json:"docIdentityId"`
	OccupationTypeID  *int64     `json:"occupationTypeId"`
	HomeCenterID      *int64     `json:"homeCenterId"`
	FatherName        *string    `json:"fatherName"`
	MotherName        *string    `json:"motherName"`
	HomeCountryID     *int64     `json:"homeCountryId"`
	HistoryNumber     *int64     `json:"historyNumber"`
	BirthCenterID     *int64     `json:"birthCenterId"`
	OriginCenterID    *int64     `json:"originCenterId"`
	OriginDistrictID  *int64     `json:"originDistrictId"`
	HomeDistrictID    *int64     `json:"homeDistrictId"`
	BirthDistrictID   *int64     `json:"birthDistrictId"`
	EthnicityID       *string    `json:"ethnicityId"`
	LanguageID        *int64     `json:"languageId"`
	Email             *string    `json:"email"`
	DisabilityID      *int64     `json:"disabilityId"`
	IncapacityID      *int64     `json:"incapacityId"`
	AuditUserID       *int64     `json:"auditUserId"`
}

// sisAfiliacionRequest es el cuerpo de POST /api/v1/sis/filiaciones.
// Replica los campos del SP webSisFiliacionesGestionar; los campos
// opcionales son punteros para enviar NULL cuando no se incluyen.
type sisAfiliacionRequest struct {
	IDSiasis                *int64     `json:"idSiasis"`
	Codigo                  *string    `json:"codigo"`
	AfiliacionDisa          *string    `json:"afiliacionDisa"`
	TipoFormato             *string    `json:"afiliacionTipoFormato"`
	NroFormato              *string    `json:"afiliacionNroFormato"`
	NroIntegrante           *string    `json:"afiliacionNroIntegrante"`
	DocumentoTipo           *string    `json:"documentoTipo"`
	CodigoEstablAdscripcion *string    `json:"codigoEstablAdscripcion"`
	AfiliacionFecha         *time.Time `json:"afiliacionFecha"`
	Paterno                 *string    `json:"paterno"`
	Materno                 *string    `json:"materno"`
	PNombre                 *string    `json:"pNombre"`
	ONombres                *string    `json:"oNombres"`
	Genero                  *string    `json:"genero"`
	FNacimiento             *time.Time `json:"fNacimiento"`
	IdDistritoDomicilio     *string    `json:"idDistritoDomicilio"`
	Estado                  *string    `json:"estado"`
	Fbaja                   *string    `json:"fBaja"`
	DocumentoNumero         *string    `json:"documentoNumero"`
	MotivoBaja              *string    `json:"motivoBaja"`
	FbajaOK                 *time.Time `json:"fBajaOk"`
	DescEESS                *string    `json:"descEESS"`
	DescEESSUbigeo          *string    `json:"descEessUbigeo"`
	Regimen                 *string    `json:"regimen"`
	TipoSeguro              *string    `json:"tipoSeguro"`
	DescTipoSeguro          *string    `json:"descTipoSeguro"`
	Contrato                *string    `json:"contrato"`
	IdPlan                  *string    `json:"idPlan"`
	IdGrupoPoblacional      *string    `json:"idGrupoPoblacional"`
	MsgConfidencial         *string    `json:"msgConfidencial"`
	IdUsuarioAuditoria      *int64     `json:"idUsuarioAuditoria"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP.
func (r sisAfiliacionRequest) toDomain() *domain.SisAfiliacion {
	return &domain.SisAfiliacion{
		IDSiasis:                r.IDSiasis,
		Codigo:                  r.Codigo,
		AfiliacionDisa:          r.AfiliacionDisa,
		TipoFormato:             r.TipoFormato,
		NroFormato:              r.NroFormato,
		NroIntegrante:           r.NroIntegrante,
		DocumentoTipo:           r.DocumentoTipo,
		CodigoEstablAdscripcion: r.CodigoEstablAdscripcion,
		AfiliacionFecha:         r.AfiliacionFecha,
		Paterno:                 r.Paterno,
		Materno:                 r.Materno,
		PNombre:                 r.PNombre,
		ONombres:                r.ONombres,
		Genero:                  r.Genero,
		FNacimiento:             r.FNacimiento,
		IdDistritoDomicilio:     r.IdDistritoDomicilio,
		Estado:                  r.Estado,
		Fbaja:                   r.Fbaja,
		DocumentoNumero:         r.DocumentoNumero,
		MotivoBaja:              r.MotivoBaja,
		FbajaOK:                 r.FbajaOK,
		DescEESS:                r.DescEESS,
		DescEESSUbigeo:          r.DescEESSUbigeo,
		Regimen:                 r.Regimen,
		TipoSeguro:              r.TipoSeguro,
		DescTipoSeguro:          r.DescTipoSeguro,
		Contrato:                r.Contrato,
		IdPlan:                  r.IdPlan,
		IdGrupoPoblacional:      r.IdGrupoPoblacional,
		MsgConfidencial:         r.MsgConfidencial,
		IdUsuarioAuditoria:      r.IdUsuarioAuditoria,
	}
}

// sisFuaForzarGuardadoRequest es el cuerpo de POST /api/v1/sis/fua.
type sisFuaForzarGuardadoRequest struct {
	IdCuentaAtencion int64 `json:"idCuentaAtencion" binding:"required"`
}

// sisFuaImprimirParams son los parámetros de GET /api/v1/sis/fua/imprimir.
type sisFuaImprimirParams struct {
	IdCuentaAtencion int64 `form:"idCuentaAtencion" binding:"required"`
}

// sisDiagnosticosParams son los parámetros de GET /api/v1/sis/diagnosticos.
type sisDiagnosticosParams struct {
	IdCuentaAtencion int64 `form:"idCuentaAtencion" binding:"required"`
}

// sisCuentaAtencionParams agrupa los parámetros de los listados que usan el
// id de la cuenta de atención (GET /api/v1/sis/medicamentos y procedimientos).
type sisCuentaAtencionParams struct {
	IdCuentaAtencion int64 `form:"idCuentaAtencion" binding:"required"`
}

// sisFuaAgregarRequest es el cuerpo de POST /api/v1/sis/fua/agregar.
type sisFuaAgregarRequest struct {
	IdCuentaAtencion int64  `json:"idCuentaAtencion" binding:"required"`
	IdEmpleado       int64  `json:"idEmpleado" binding:"required"`
	NombrePc         string `json:"nombrePc" binding:"omitempty"`
}

// createTriajeRequest es el cuerpo de POST /api/v1/triaje. Cada campo es
// puntero para que el frontend pueda enviar solo los datos que recopiló;
// los que faltan se persisten como NULL en el SP.
// parseDate convierte un puntero a string con fecha "YYYY-MM-DD" a un
// *time.Time. Si el string es nil o vacío retorna nil; si el formato es
// inválido retorna nil (se tratará como NULL al persistir).
func parseDate(s *string) *time.Time {
	if s == nil || *s == "" {
		return nil
	}
	t, err := time.Parse("2006-01-02", *s)
	if err != nil {
		return nil
	}
	return &t
}

type createTriajeRequest struct {
	IDTriaje                  *int64     `json:"idTriaje"`
	DocIdentityType           *int64     `json:"idDocIdentidad"`
	DocumentNumber            *string    `json:"nroDocumento"`
	PaternalSurname           *string    `json:"apellidoPaterno"`
	MaternalSurname           *string    `json:"apellidoMaterno"`
	FirstName                 *string    `json:"primerNombre"`
	SecondName                *string    `json:"segundoNombre"`
	ThirdName                 *string    `json:"tercerNombre"`
	SexTypeID                 *int64     `json:"idSexo"`
	DateOfBirth               *time.Time `json:"fechaNacimiento"`
	Phone                     *string    `json:"telefono"`
	HomeDepartmentID          *int64     `json:"idDepartamentoDomicilio"`
	HomeProvinceID            *int64     `json:"idProvinciaDomicilio"`
	HomeDistrictID            *int64     `json:"idDistritoDomicilio"`
	HomeCommunityID           *int64     `json:"idComunidadDomicilio"`
	HomeAddress               *string    `json:"direccion"`
	IsTrafficAccident         *int64     `json:"idEsAccidenteTransito"`
	FundingSourceID           *int64     `json:"idFuenteFinanciamiento"`
	Email                     *string    `json:"email"`
	MaritalStatusID           *int64     `json:"idEstadoCivil"`
	HeartRate                 *int64     `json:"frecCardiaca"`
	Temperature               *float64   `json:"temperatura"`
	BloodPressure             *string    `json:"presionArterial"`
	Oxygen                    *int64     `json:"saturacion"`
	RespiratoryRate           *int64     `json:"frecRespiratoria"`
	FiO2                      *int64     `json:"fiO2"`
	Weight                    *float64   `json:"peso"`
	Height                    *float64   `json:"talla"`
	BMI                       *float64   `json:"imc"`
	EvolutionTimeQuantity     *int64     `json:"tiempoEvolucionCantidad"`
	EvolutionTimeQuantityUnit *string    `json:"tiempoEvolucionCantidadUnidad"`
	PainScale                 *int64     `json:"escalaDolor"`
	GlasgowScale              *int64     `json:"escalaGlasgow"`
	PriorityTypeID            *int64     `json:"idTipoPrioridad"`
	ServiceID                 *int64     `json:"idServicio"`
	Motivo                    *string    `json:"motivo"`
	IsPregnant                *int64     `json:"gestante"`
	ArrivalStateID            *int64     `json:"idEstadollego"`
	FUR                       *string    `json:"fur"`
	EsGestante                *bool      `json:"esGestante"`
	EdadGestacional           *int64     `json:"edadGestacional"`
	FPP                       *string    `json:"fpp"`
	NroControlesPrenatales    *int64     `json:"nroControlesPrenatales"`
	MovimientosFetales        *int64     `json:"movimientosFetales"`
	Photo                     *string    `json:"foto"`
	EmployeeID                *int64     `json:"idEmpleado"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP.
func (r createTriajeRequest) toDomain() *domain.Triage {
	return &domain.Triage{
		IDTriaje:                  r.IDTriaje,
		DocIdentityID:             r.DocIdentityType,
		DocumentNumber:            r.DocumentNumber,
		PaternalSurname:           r.PaternalSurname,
		MaternalSurname:           r.MaternalSurname,
		FirstName:                 r.FirstName,
		SecondName:                r.SecondName,
		ThirdName:                 r.ThirdName,
		SexTypeID:                 r.SexTypeID,
		DateOfBirth:               r.DateOfBirth,
		Phone:                     r.Phone,
		HomeDepartmentID:          r.HomeDepartmentID,
		HomeProvinceID:            r.HomeProvinceID,
		HomeDistrictID:            r.HomeDistrictID,
		HomeCommunityID:           r.HomeCommunityID,
		HomeAddress:               r.HomeAddress,
		IsTrafficAccident:         r.IsTrafficAccident,
		FundingSourceID:           r.FundingSourceID,
		Email:                     r.Email,
		MaritalStatusID:           r.MaritalStatusID,
		HeartRate:                 r.HeartRate,
		Temperature:               r.Temperature,
		BloodPressure:             r.BloodPressure,
		OxygenSaturation:          r.Oxygen,
		RespiratoryRate:           r.RespiratoryRate,
		FiO2:                      r.FiO2,
		Weight:                    r.Weight,
		Height:                    r.Height,
		BMI:                       r.BMI,
		EvolutionTimeQuantity:     r.EvolutionTimeQuantity,
		EvolutionTimeQuantityUnit: r.EvolutionTimeQuantityUnit,
		PainScale:                 r.PainScale,
		GlasgowScale:              r.GlasgowScale,
		PriorityTypeID:            r.PriorityTypeID,
		ServiceID:                 r.ServiceID,
		Motivo:                    r.Motivo,
		IsPregnant:                r.IsPregnant,
		ArrivalStateID:            r.ArrivalStateID,
		FUR:                       parseDate(r.FUR),
		EsGestante:                r.EsGestante,
		EdadGestacional:           r.EdadGestacional,
		FPP:                       parseDate(r.FPP),
		NroControlesPrenatales:    r.NroControlesPrenatales,
		MovimientosFetales:        r.MovimientosFetales,
		Photo:                     r.Photo,
		EmployeeID:                r.EmployeeID,
	}
}

// createAdmissionFromTriageRequest es el cuerpo de POST
// /api/v1/triaje/admision. Los campos opcionales son punteros para que el
// frontend envíe solo los que tiene; los que falten se persisten como NULL.
type createAdmissionFromTriageRequest struct {
	IDTriaje            *int64  `json:"idTriaje" binding:"required"`
	IDPacienteTriaje    *int64  `json:"idPacienteTriaje" binding:"required"`
	NroDocumento        *string `json:"nroDocumento"`
	IDMedico            *int64  `json:"idMedico"`
	NombreAcompanante   *string `json:"nombreAcompanante"`
	TelefonoAcompanante *string `json:"telefonoAcompanante"`
	DireccionPaciente   *string `json:"direccionPaciente"`
	Observacion         *string `json:"observacion"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP.
func (r createAdmissionFromTriageRequest) toDomain() *domain.AdmisionDesdeTriaje {
	return &domain.AdmisionDesdeTriaje{
		IDTriaje:            r.IDTriaje,
		IDPacienteTriaje:    r.IDPacienteTriaje,
		NroDocumento:        r.NroDocumento,
		IDMedico:            r.IDMedico,
		NombreAcompanante:   r.NombreAcompanante,
		TelefonoAcompanante: r.TelefonoAcompanante,
		DireccionPaciente:   r.DireccionPaciente,
		Observacion:         r.Observacion,
	}
}

// toDomain mapea el request HTTP al objeto de dominio.
func (r updatePatientRequest) toDomain() domain.PatientUpdate {
	return domain.PatientUpdate{
		BirthCountryID:    r.BirthCountryID,
		MaternalSurname:   r.MaternalSurname,
		HomeAddress:       r.HomeAddress,
		OriginCountryID:   r.OriginCountryID,
		PaternalSurname:   r.PaternalSurname,
		FirstName:         r.FirstName,
		SecondName:        r.SecondName,
		ThirdName:         r.ThirdName,
		DateOfBirth:       r.DateOfBirth,
		DocumentNumber:    r.DocumentNumber,
		Phone:             r.Phone,
		Cellphone:         r.Cellphone,
		AutoGenerated:     r.AutoGenerated,
		SexTypeID:         r.SexTypeID,
		OriginID:          r.OriginID,
		EducationDegreeID: r.EducationDegreeID,
		MaritalStatusID:   r.MaritalStatusID,
		DocIdentityID:     r.DocIdentityID,
		OccupationTypeID:  r.OccupationTypeID,
		HomeCenterID:      r.HomeCenterID,
		FatherName:        r.FatherName,
		MotherName:        r.MotherName,
		HomeCountryID:     r.HomeCountryID,
		HistoryNumber:     r.HistoryNumber,
		BirthCenterID:     r.BirthCenterID,
		OriginCenterID:    r.OriginCenterID,
		OriginDistrictID:  r.OriginDistrictID,
		HomeDistrictID:    r.HomeDistrictID,
		BirthDistrictID:   r.BirthDistrictID,
		EthnicityID:       r.EthnicityID,
		LanguageID:        r.LanguageID,
		Email:             r.Email,
		DisabilityID:      r.DisabilityID,
		IncapacityID:      r.IncapacityID,
		AuditUserID:       r.AuditUserID,
	}
}

// EvolucionCreateRequest representa el payload recibido desde Angular
// para registrar una nueva evolución médica SOAP.
type EvolucionCreateRequest struct {
	IDPaciente       int64                `json:"idPaciente" binding:"required"`
	IDMedico         int64                `json:"idMedico" binding:"required"`
	IDCita           *int64               `json:"idCita"`
	MotivoAtencion   *string              `json:"motivoAtencion"`
	DetalleMotivo    *string              `json:"detalleMotivo"`
	SubjetivoDetalle *string              `json:"subjetivoDetalle"`
	PresionArterial  *string              `json:"presionArterial"`
	FrecCardiaca     *int                 `json:"frecCardiaca"`
	FrecRespiratoria *int                 `json:"frecRespiratoria"`
	Temperatura      *float64             `json:"temperatura"`
	SaturacionO2     *int                 `json:"saturacionO2"`
	Peso             *float64             `json:"peso"`
	Talla            *float64             `json:"talla"`
	IMC              *float64             `json:"imc"`
	Glucemia         *int                 `json:"glucemia"`
	EstadoClinico    *string              `json:"estadoClinico"`
	Pronostico       *string              `json:"pronostico"`
	PlanDetalle      *string              `json:"planDetalle"`
	Diagnosticos     []DiagnosticoRequest `json:"diagnosticos"`
}

type DiagnosticoRequest struct {
	CIE10       string `json:"cie10" binding:"required"`
	Descripcion string `json:"descripcion" binding:"required"`
	Tipo        string `json:"tipo"`
	Condicion   string `json:"condicion"`
	Estado      string `json:"estado"`
}

// createTriajeConsultaRequest es el cuerpo de POST /api/v1/triaje/consulta.
// Los signos vitales se envían como texto (el SP AtencionesTriajeAgregar
// los declara VARCHAR(10)); los opcionales son punteros para enviar NULL
// cuando el frontend no los recopiló.
type createTriajeConsultaRequest struct {
	IdAtencion        int64   `json:"idAtencion" binding:"required"`
	IdPaciente        int64   `json:"idPaciente" binding:"required"`
	IdEmpleado        int64   `json:"idEmpleado" binding:"required"`
	Talla             *string `json:"talla"`
	Peso              *string `json:"peso"`
	Temperatura       *string `json:"temperatura"`
	Pulso             *string `json:"pulso"`
	FrecRespiratoria  *string `json:"frecRespiratoria"`
	FrecCardiaca      *string `json:"frecCardiaca"`
	FrecCardiacaFetal *string `json:"frecCardiacaFetal"`
	PerimCefalico     *string `json:"perimCefalico"`
	Origen            *string `json:"origen"`
	PerimAbdominal    *string `json:"perimAbdominal"`
	SAT02             *string `json:"sat02"`
	FI02              *string `json:"fi02"`
	PresionArterial   *string `json:"presionArterial"`
	Hemoglobina       *string `json:"hemoglobina"`
	Observacion       *string `json:"observacion"`
	IMC               *string `json:"imc"`
	Gestante          *string `json:"gestante"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP
// AtencionesTriajeAgregar.
func (r createTriajeConsultaRequest) toDomain() *domain.TriajeConsulta {
	return &domain.TriajeConsulta{
		IdAtencion:        r.IdAtencion,
		IdPaciente:        r.IdPaciente,
		IdEmpleado:        r.IdEmpleado,
		Talla:             r.Talla,
		Peso:              r.Peso,
		Temperatura:       r.Temperatura,
		Pulso:             r.Pulso,
		FrecRespiratoria:  r.FrecRespiratoria,
		FrecCardiaca:      r.FrecCardiaca,
		FrecCardiacaFetal: r.FrecCardiacaFetal,
		PerimCefalico:     r.PerimCefalico,
		Origen:            r.Origen,
		PerimAbdominal:    r.PerimAbdominal,
		SAT02:             r.SAT02,
		FI02:              r.FI02,
		PresionArterial:   r.PresionArterial,
		Hemoglobina:       r.Hemoglobina,
		Observacion:       r.Observacion,
		IMC:               r.IMC,
		Gestante:          r.Gestante,
	}
}

// triajeConsultaEstadoRequest es el cuerpo de PUT /api/v1/triaje/consulta/:id/estado.
type triajeConsultaEstadoRequest struct {
	Estado string `json:"estado" binding:"required"`
}
