package domain

import "time"

// PatientUpdate transporta los datos editables de un paciente hacia el SP
// usp_go_ModificarPaciente. Todos los campos son opcionales; un puntero nil
// se envía como NULL al procedimiento. Es el equivalente Go del schema
// PacienteUpdate del proyecto FastAPI.
type PatientUpdate struct {
	BirthCountryID    *int64
	MaternalSurname   *string
	HomeAddress       *string
	OriginCountryID   *int64
	PaternalSurname   *string
	FirstName         *string
	SecondName        *string
	ThirdName         *string
	DateOfBirth       *time.Time
	DocumentNumber    *string
	Phone             *string
	Cellphone         *string
	AutoGenerated     *string
	SexTypeID         *int64
	OriginID          *int64
	EducationDegreeID *int64
	MaritalStatusID   *int64
	DocIdentityID     *int64
	OccupationTypeID  *int64
	HomeCenterID      *int64
	FatherName        *string
	MotherName        *string
	HomeCountryID     *int64
	HistoryNumber     *int64
	BirthCenterID     *int64
	OriginCenterID    *int64
	OriginDistrictID  *int64
	HomeDistrictID    *int64
	BirthDistrictID   *int64
	EthnicityID       *string
	LanguageID        *int64
	Email             *string
	DisabilityID      *int64
	IncapacityID      *int64
	// Datos de la madre tutor. Ojo: MotherName es el campo legacy
	// @NombreMadre; estos cinco son los campos desnormalizados @Madre*.
	MotherDocumentNumber  *string
	MotherPaternalSurname *string
	MotherMaternalSurname *string
	MotherFirstName       *string
	MotherSecondName      *string
	AuditUserID           *int64
}
